---
abstract: 'check code for FIXMEs.'
author:
  - 'Graham Ollis <plicease@wdlabs.com>'
  - 'Edmund von der Burg <evdb@ecclestoad.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Fixme
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  ExtUtils::MakeMaker: 0
  File::Find: 0
  Test::Builder: 0
  Test::More: 0
  perl: 5.006000
resources:
  bugtracker: https://github.com/plicease/Test-Fixme/issues
  homepage: http://search.cpan.org/dist/Test-Fixme/
  repository: git://github.com/plicease/Test-Fixme.git
version: 0.05
